import "~/styles/globals.css";

import { Nunito } from "next/font/google";
import { cn } from "~/lib/utils";

const nunito = Nunito({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-nunito",
  display: "swap",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={cn("overflow-x-hidden", ...nunito.className)}>
      <body className="overflow-x-hidden text-gray-600">{children}</body>
    </html>
  );
}
